### ISSUE TITLE
Issue in Bash Script Step - Release pipeline

### ISSUE THREAD

**Issue by vishalrana11** [srijiths/MLOps-IRIS#5]
Hi Srijith,

First of all, I would like to thank you for such a great presentation on youtube. 

I am facing permission denied issue in bash script step of release pipeline - UAT and I tried a lot for last 2 days to resolve it but in vain. 

Error : 

2021-05-29T09:54:25.1905575Z /home/vsts/work/_temp/89785997-11ae-403b-a07d-1895942d71c5.sh: line 3: /home/vsts/work/r1/a/_mlops111-CI/iris_classifier/a/install-requirements.sh: Permission denied

artifcat name : _mlops111-CI

Inline script used : $(System.DefaultWorkingDirectory)/_mlops111-CI/iris_classifier/a/install-requirements.sh

Also tried with/without working directory : $(System.DefaultWorkingDirectory)/_mlops111-CI/iris_classifier

Could you please help in resolving this issue.
<img width="951" alt="1" src="https://user-images.githubusercontent.com/40214948/120066454-21d17500-c094-11eb-9d7a-e0ee0937e87c.PNG">
<img width="778" alt="2" src="https://user-images.githubusercontent.com/40214948/120066457-239b3880-c094-11eb-9a90-ec5bb07e5643.PNG">
<img width="957" alt="3" src="https://user-images.githubusercontent.com/40214948/120066459-2433cf00-c094-11eb-87d7-f2bb3aa820c5.PNG">

Best Regards.

**Comment by srijiths** [comment]
Can you change the Bash Script "Type" as "File" instead of the current selection "inline". WOrking directory is not required in this case. There is no issue providing it.  But if you do in any steps , provide till the "a" ( the leaf node of the directory "

**Comment by vishalrana11** [comment]
Thank you Srijith!! The issue is resolved now and UAT is successful. :)
