### ISSUE TITLE
Create/Use Compute is giving an error AZ Login

### ISSUE THREAD

**Issue by ashwarhussain** [srijiths/MLOps-IRIS#6]
Hello Srijith,

awesome session and very nice demo. Thank a lot. 

I am having an error at the Use/Create Compute step in build pipeline. Error says 

ERROR: {'Azure-cli-ml Version': '1.33.0', 'Error': AuthenticationException:
	Message: Could not retrieve user token. Please run 'az login'
	InnerException Please run 'az login' to setup account.
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "inner_error": {
            "code": "Authentication"
        },
        "message": "Could not retrieve user token. Please run 'az login'"
    }
}}

and the task of register model I get another error which says "ERROR: {'Azure-cli-ml Version': '1.33.0', 'Error': FileNotFoundError(2, 'No such file or directory')}"

can you please help me out here.

Regards,
Ashwar.

**Comment by srijiths** [comment]
Recently due to azure ml sdk and azure ml cli version updates, there are lot of such issues.  Try checking azure repo for similar issues. I dont have an Azure Environment to test it now.

**Comment by anjurc** [comment]
Hi,
@ashwarhussain did you close this error? I too had the same

**Comment by anjurc** [comment]
Hi, 
Solve the issue using the azure cli command - az login
