### ISSUE TITLE
Anyone stuck at Upload Data to Blobstore step

### ISSUE THREAD

**Issue by Amit-sood** [srijiths/MLOps-IRIS#7]
Following command fails 

`az ml datastore upload -w $(ml.workspace) -g $(ml.resourceGroup) -n $(az ml datastore show -w $(ml.workspace) -g $(ml.resourceGroup) --query name -o tsv) -p data -u irisdata`

Is there an update repo of code as per the changes in latest azure ml sdk?

**Comment by srijiths** [comment]
Recently, someone followed the same thing based on this repo and it was successful. Check your error logs and debug pls.

**Comment by DevOps2MLops** [comment]
yes even i am facing issue.
@srijiths  here is the error

/opt/hostedtoolcache/Python/3.8.16/x64/bin/az account set --subscription 1bc4e065-80cd-48c1-92e1-3b02f9718b33
/usr/bin/bash /home/vsts/work/_temp/azureclitaskscript1680248569007.sh
ERROR: UserErrorException:
	Message: src_path must be a directory.
	InnerException None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "src_path must be a directory."
    }
}
##[error]Script failed with exit code: 1
/opt/hostedtoolcache/Python/3.8.16/x64/bin/az account clear
Finishing: Upload Data to Default Blob
