### ISSUE TITLE
Can someone share AKS CLI commands

### ISSUE THREAD

**Issue by moeenkhurram** [srijiths/MLOps-IRIS#8]
In [Devops_deploy.txt](https://github.com/srijiths/MLOps-IRIS/blob/master/CLI%20Commands/Deploy/Devops_deploy.txt) only CLI commands for Deploy IRIS Model to Azure Container Instances are given

**Comment by srijiths** [comment]
1. You can use the same deploy command and change the ACI configuration with [aksDeploymentConfig.yml](https://github.com/srijiths/MLOps-IRIS/blob/master/deployment/aksDeploymentConfig.yml) . 
2. Also you need to add an additional ```--ct``` parameter in the deploy command ( This is the AKS Cluster name which is created )

Make sure you have a AKS cluster created before this deploy step. In this repo , AKS creation step is not used in the pipeline assuming the deployment is ACI.

**Comment by moeenkhurram** [comment]
**Create AKS cluster**
`az ml computetarget create aks -g $(ml.resourceGroup)  -w $(ml.workspace)  -n $(aks.clusterName) -l eastus2 -s Standard_A2_v2 --verbose -a 1 --cluster-purpose DevTest`

**Deploy model to AKS for Production**
`az ml model deploy --name $(service_name) -g $(ml.resourceGroup) -w $(ml.workspace)  --ct $(aks.clusterName) -f model.json --ic inferenceConfig.yml --dc aksDeploymentConfig.yml  --overwrite`
